openapi: 3.0.3
info:
  title: Core API - 文件服务
  description: 包含文件上传、下载等核心接口
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8888/api/file
    description: 本地开发环境服务地址 - 文件相关接口
paths:
  /upload:
    post:
      summary: 文件上传接口
      description: |
        上传文件到服务器，支持秒传功能（基于文件 hash 判断文件是否已存在）。
        
        **智能压缩：**
        - **视频文件**：自动使用 ffmpeg 压缩（H.264 编码，CRF=23，音频 128k）
        - **图片文件**：自动压缩并限制尺寸（最大 1920x1080，JPEG 质量 85）
        - **其他文件**：不压缩，直接上传
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **文件大小限制：** 
        - 最大支持 10GB 文件上传
        - 建议视频文件不超过 5GB，以获得更好的用户体验
        
        **支持的视频格式（会自动压缩）：**
        - .mp4, .avi, .mov, .mkv, .flv, .wmv, .webm, .m4v
        
        **支持的图片格式（会自动压缩）：**
        - .jpg, .jpeg, .png, .gif, .bmp, .webp
        - 压缩规则：最大宽度 1920px，最大高度 1080px，保持宽高比
        - JPEG 质量：85（平衡画质和文件大小）
        
        **秒传机制：**
        - 系统会先计算文件的 MD5 hash
        - 如果文件已存在（hash 相同），直接返回已有文件标识，无需重复上传
      operationId: UploadFileHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: |
                    上传的文件对象
                    
                    - 视频文件（.mp4, .avi, .mov 等）：自动压缩
                    - 图片文件（.jpg, .png 等）：自动压缩并限制尺寸
                    - 其他文件：不压缩，直接上传
              required:
                - file
      responses:
        '200':
          description: 文件上传成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'
        '400':
          description: 请求参数错误
        '413':
          description: 文件过大（Request Entity Too Large），超过 10GB 限制
        '500':
          description: 服务器内部错误
  /url:
    post:
      summary: 获取文件下载链接
      description: |
        获取当前用户文件的下载链接。
        
        **功能说明：**
        - 仅支持下载自己的文件
        - 返回带过期时间的下载链接
        - 过期时间有上限（默认 1 小时，最长 7 天）
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
      operationId: DownloadURLHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DownloadURLRequest'
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadURLResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 未授权或 token 无效
        '404':
          description: 文件不存在
        '500':
          description: 服务器内部错误
  /user/list:
    post:
      summary: 获取用户文件列表
      description: |
        获取当前登录用户的文件列表，支持分页和文件夹筛选。
        
        **功能说明：**
        - 查询用户的文件仓库（user_repository 表）中的文件
        - 支持按文件夹 ID 筛选（查看指定文件夹下的文件）
        - 支持分页查询
        - 返回文件详细信息（包括文件大小、扩展名等）
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **使用场景：**
        1. 显示用户网盘首页（根目录文件列表）
        2. 进入某个文件夹，查看该文件夹下的文件
        3. 分页加载大量文件
        
        **数据来源：**
        - 从 user_repository 表查询（用户个人文件关联表）
        - 通过 repository_identity 关联到 repository_pool 表获取文件详情
      operationId: UserFileListHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFileListRequest'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFileListResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 未授权或 token 无效
        '500':
          description: 服务器内部错误
  /user/file/name/update:
    post:
      summary: 修改文件名称
      description: |
        修改用户文件仓库中的文件名称（重命名功能）。
        
        **功能说明：**
        - 修改用户个人文件列表中的文件名称
        - 只修改 user_repository 表中的记录（不影响其他用户）
        - 不修改物理文件（repository_pool 表不变）
        - 支持重命名为任意名称
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **使用场景：**
        1. 用户对已保存的文件进行重命名
        2. 整理文件时修改文件名
        3. 为分享的文件设置自定义名称
        
        **注意事项：**
        - 只能修改自己的文件名称
        - 文件名不能为空
        - 修改后不影响其他用户的文件名
      operationId: UserFileNameUpdateHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFileNameUpdateRequest'
      responses:
        '200':
          description: 修改成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFileNameUpdateResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 未授权或 token 无效
        '403':
          description: 无权修改此文件
        '404':
          description: 文件不存在
        '500':
          description: 服务器内部错误
  /user/folder/create:
    post:
      summary: 创建文件夹
      description: |
        在用户网盘中创建新文件夹。
        
        **功能说明：**
        - 在指定位置创建文件夹
        - 支持多级文件夹（通过 parent_id 指定父文件夹）
        - 文件夹也存储在 user_repository 表中
        - 文件夹不关联 repository_pool（无实际文件）
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **使用场景：**
        1. 用户整理文件，创建分类文件夹
        2. 创建多级目录结构
        3. 在文件夹内创建子文件夹
        
        **实现原理：**
        - 在 user_repository 表中插入一条记录
        - ext 字段为空或特殊标记（表示文件夹）
        - repository_identity 为空（文件夹无实际文件）
        - 其他文件可以设置 parent_id 为此文件夹的 id
        
        **注意事项：**
        - 文件夹名称不能为空
        - 同一目录下不建议有重名文件夹
        - parent_id = 0 表示在根目录创建
      operationId: UserFolderCreateHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFolderCreateRequest'
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFolderCreateResponse'
        '400':
          description: 请求参数错误（文件夹名为空等）
        '401':
          description: 未授权或 token 无效
        '404':
          description: 父文件夹不存在
        '500':
          description: 服务器内部错误
  /user/folder/delete:
    delete:
      summary: 删除文件或文件夹
      description: |
        删除用户网盘中的文件或文件夹（支持递归删除）。
        
        **功能说明：**
        - 删除单个文件或整个文件夹
        - 删除文件夹时自动递归删除所有子项
        - 使用软删除（更新 deleted_at 字段）
        - 只能删除自己的文件，不影响其他用户
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **使用场景：**
        1. 删除不需要的文件
        2. 清理整个文件夹（包括所有子文件夹和文件）
        3. 整理网盘空间
        
        **删除规则：**
        - 删除文件：直接删除该文件记录
        - 删除文件夹：递归删除文件夹及其所有子项
        - 软删除：数据标记为已删除但保留在数据库
        - 物理文件：repository_pool 中的文件不会删除（其他用户可能使用）
        
        **注意事项：**
        - 删除操作不可逆（软删除可恢复，但需要管理员操作）
        - 删除文件夹会删除其中所有内容
        - 建议删除前二次确认
      operationId: UserFolderDeleteHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFolderDeleteRequest'
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFolderDeleteResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 未授权或 token 无效
        '403':
          description: 无权删除此文件或文件夹
        '404':
          description: 文件或文件夹不存在
        '500':
          description: 服务器内部错误
  /user/file/move:
    put:
      summary: 移动文件或文件夹
      description: |
        将文件或文件夹移动到另一个位置。
        
        **功能说明：**
        - 移动文件到其他文件夹
        - 移动文件夹到其他位置
        - 支持移动到根目录（parent_id = 0）
        - 只修改 parent_id，不影响文件内容
        
        **认证方式：**
        - 必须在 HTTP Header 中携带 JWT token
        - Header: `Authorization: Bearer <your_token>`
        
        **使用场景：**
        1. 整理文件，移动到对应文件夹
        2. 调整目录结构
        3. 将子文件夹提升到上级目录
        
        **移动规则：**
        - 只能移动自己的文件/文件夹
        - 目标文件夹必须存在（除非移动到根目录）
        - 移动文件夹时，其子项的层级关系保持不变
        
        **注意事项：**
        - parent_id = 0 表示移动到根目录
        - 移动操作会立即生效
      operationId: UserFileMoveHandler
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFileMoveRequest'
      responses:
        '200':
          description: 移动成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFileMoveResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 未授权或 token 无效
        '403':
          description: 无权移动此文件或文件夹
        '404':
          description: 文件、文件夹或目标位置不存在
        '500':
          description: 服务器内部错误
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT Token 认证
        
        请在 HTTP Header 中添加：
        ```
        Authorization: Bearer <your_token>
        ```
        
        获取 token 的方式：
        1. 调用登录接口 `/api/users/login`
        2. 调用注册接口 `/api/users/register`
  schemas:
    UploadFileResponse:
      type: object
      description: 文件上传响应结果
      properties:
        message:
          type: string
          description: 上传处理结果信息
          example: "文件上传开始"
      required: [message]
      nullable: false
    
    DownloadURLRequest:
      type: object
      description: 下载链接请求
      properties:
        repository_identity:
          type: string
          description: 文件仓库标识（repository_pool.identity）
          example: "file_identity_abc123"
        expires:
          type: integer
          format: int32
          description: |
            过期时间（秒）
            - <=0 使用默认 1 小时
            - 最大 7 天
          example: 3600
      required: [repository_identity]
    
    DownloadURLResponse:
      type: object
      description: 下载链接响应
      properties:
        url:
          type: string
          description: 带签名的下载链接
          example: "https://oss-example.aliyuncs.com/xxx?signature=..."
        expires:
          type: integer
          format: int32
          description: 链接有效期（秒）
          example: 3600
      required: [url, expires]
    
    UserFileListRequest:
      type: object
      description: 用户文件列表查询请求
      properties:
        id:
          type: integer
          format: int64
          description: |
            文件夹 ID（parent_id）
            - 不传或传 0：查询根目录下的文件
            - 传具体 ID：查询指定文件夹下的文件
          example: 0
        page:
          type: integer
          format: int64
          description: |
            页码（从 1 开始）
            默认：1
          example: 1
          default: 1
        size:
          type: integer
          format: int64
          description: |
            每页数量
            默认：20
          example: 20
          default: 20
    
    UserFileListResponse:
      type: object
      description: 用户文件列表响应
      properties:
        list:
          type: array
          description: 文件列表
          items:
            $ref: '#/components/schemas/UserFile'
        count:
          type: integer
          format: int64
          description: 文件总数（用于分页）
          example: 100
      required: [list, count]
    
    UserFile:
      type: object
      description: 用户文件信息
      properties:
        id:
          type: integer
          format: int64
          description: 用户文件记录 ID（user_repository 表主键）
          example: 1
        identity:
          type: string
          description: 用户文件记录唯一标识（user_repository.identity）
          example: "user_repo_identity_abc123"
        name:
          type: string
          description: 文件名称
          example: "我的文档.pdf"
        ext:
          type: string
          description: 文件扩展名
          example: ".pdf"
        size:
          type: integer
          format: int64
          description: 文件大小（字节）
          example: 1048576
        repository_identity:
          type: string
          description: |
            文件仓库标识（关联到 repository_pool 表）
            可用于文件下载、删除等操作
          example: "file_identity_xyz789"
      required: [id, identity, name, ext, size, repository_identity]
    
    UserFileNameUpdateRequest:
      type: object
      description: 文件重命名请求
      properties:
        identity:
          type: string
          description: |
            用户文件记录标识（user_repository.identity）
            从文件列表接口获取
          example: "user_repo_identity_abc123"
        name:
          type: string
          description: |
            新的文件名称
            - 不能为空
            - 可以包含扩展名，也可以不包含
            - 建议保留原有扩展名
          example: "我的重要文档.pdf"
      required: [identity, name]
    
    UserFileNameUpdateResponse:
      type: object
      description: 文件重命名响应（空响应，成功返回 200）
      properties: {}
    
    UserFolderCreateRequest:
      type: object
      description: 创建文件夹请求
      properties:
        parent_id:
          type: integer
          format: int64
          description: |
            父文件夹 ID
            - 0：在根目录创建
            - 其他值：在指定文件夹下创建子文件夹
          example: 0
        name:
          type: string
          description: |
            文件夹名称
            - 不能为空
            - 建议避免特殊字符
            - 同一目录下不建议重名
          example: "我的文档"
      required: [parent_id, name]
    
    UserFolderCreateResponse:
      type: object
      description: 创建文件夹响应
      properties:
        identity:
          type: string
          description: |
            文件夹记录的唯一标识（user_repository.identity）
            可用于后续操作（如创建子文件夹、移动文件等）
          example: "folder_identity_abc123"
      required: [identity]
    
    UserFolderDeleteRequest:
      type: object
      description: 删除文件或文件夹请求
      properties:
        identity:
          type: string
          description: |
            要删除的文件或文件夹标识（user_repository.identity）
            - 删除文件：直接删除该文件
            - 删除文件夹：递归删除文件夹及其所有子项
          example: "folder_identity_abc123"
      required: [identity]
    
    UserFolderDeleteResponse:
      type: object
      description: 删除文件或文件夹响应（空响应，成功返回 200）
      properties: {}
    
    UserFileMoveRequest:
      type: object
      description: 移动文件或文件夹请求
      properties:
        identity:
          type: string
          description: |
            要移动的文件或文件夹标识（user_repository.identity）
            从文件列表接口获取
          example: "file_identity_abc123"
        parent_id:
          type: integer
          format: int64
          description: |
            目标父文件夹 ID
            - 0：移动到根目录
            - 其他值：移动到指定文件夹下
          example: 10
        name:
          type: string
          description: |
            移动后的名称（可选）
            - 如果不传或为空，保持原名称
            - 如果传入新名称，同时完成重命名
          example: "移动后的文档.pdf"
      required: [identity, parent_id]
    
    UserFileMoveResponse:
      type: object
      description: 移动文件或文件夹响应（空响应，成功返回 200）
      properties: {}
