openapi: 3.0.3
info:
  title: Core API - 用户中心服务
  description: |
    包含用户登录、注册核心接口。
    
    响应包裹：所有接口统一返回结构 {code,msg,data}
    - code: 数字状态码（0 为成功）
    - msg: 文本消息（错误信息或提示）
    - data: 实际业务数据（各接口定义的响应体）
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8888/api/users
    description: 本地开发环境服务地址 - 用户相关接口
paths:
  /login:
    post:
      summary: 用户登录接口
      description: 接收用户名/邮箱和密码，返回登录令牌和用户名
      operationId: LoginHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseLoginResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 用户名或密码错误
  /register:
    post:
      summary: 用户注册接口
      description: 接收用户名、邮箱和密码，完成注册并返回令牌和用户名
      operationId: RegisterHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterResponse'
        '400':
          description: 请求参数错误（如用户名已存在、邮箱格式非法）
  /password/update:
    post:
      summary: 修改用户密码接口
      description: 校验旧密码后修改为新密码
      operationId: ChangePasswordHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: 修改密码成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseChangePasswordResponse'
        '400':
          description: 请求参数错误或旧密码错误
        '401':
          description: 认证失败
  /password/reset:
    post:
      summary: 忘记密码重置接口
      description: 通过邮箱验证码重置密码
      operationId: ResetPasswordHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: 重置密码成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseResetPasswordResponse'
        '400':
          description: 请求参数错误或验证码错误
  /detail:
    post:
      summary: 获取用户详情接口
      description: 根据身份标识获取用户详细信息
      operationId: UserDetailHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetailRequest'
      responses:
        '200':
          description: 获取用户详情成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseUserDetailResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 认证失败
  /send-verification-code:
    post:
      summary: 发送邮箱验证码接口
      description: 接收邮箱地址，发送验证码到指定邮箱
      operationId: SendVerificationCodeHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendVerificationCodeRequest'
      responses:
        '200':
          description: 邮箱验证码发送成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSendVerificationCodeResponse'
        '400':
          description: 请求参数错误
components:
  schemas:
    ApiResponseLoginResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/LoginResponse'
      required: [code, msg, data]
      nullable: false

    ApiResponseRegisterResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/RegisterResponse'
      required: [code, msg, data]
      nullable: false

    ApiResponseChangePasswordResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/ChangePasswordResponse'
      required: [code, msg, data]
      nullable: false

    ApiResponseResetPasswordResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/ResetPasswordResponse'
      required: [code, msg, data]
      nullable: false

    ApiResponseUserDetailResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/UserDetailResponse'
      required: [code, msg, data]
      nullable: false

    ApiResponseSendVerificationCodeResponse:
      type: object
      description: 通用响应包裹
      properties:
        code:
          type: integer
          format: int32
          example: 0
        msg:
          type: string
          example: "ok"
        data:
          $ref: '#/components/schemas/SendVerificationCodeResponse'
      required: [code, msg, data]
      nullable: false
    LoginRequest:
      type: object
      description: 用户登录请求参数
      properties:
        name:
          type: string
          description: 用户名或邮箱
          example: "zhangsan"
        password:
          type: string
          description: 用户密码
          example: "123456Abc"
      nullable: false
    RegisterRequest:
      type: object
      description: 用户注册请求参数
      properties:
        name:
          type: string
          description: 用户名
          example: "zhangsan"
        email:
          type: string
          format: email
          description: 用户邮箱
          example: "zhangsan@example.com"
        password:
          type: string
          description: 用户密码
          example: "123456Abc"
        code:
          type: string
          description: 邮箱验证码
          example: "123456"
      nullable: false
    LoginResponse:
      type: object
      description: 用户登录响应结果
      properties:
        token:
          type: string
          description: 登录令牌（用于后续接口认证）
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        name:
          type: string
          description: 用户名
          example: "zhangsan"
      required: [token, name]
      nullable: false
    RegisterResponse:
      type: object
      description: 用户注册响应结果
      properties:
        token:
          type: string
          description: 注册成功令牌（用于后续接口认证）
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        name:
          type: string
          description: 用户名
          example: "zhangsan"
      required: [token, name]
      nullable: false
    ChangePasswordRequest:
      type: object
      description: 修改密码请求参数
      properties:
        identity:
          type: string
          description: 用户身份标识
          example: "user_identity_12345"
        old_password:
          type: string
          description: 旧密码
          example: "oldPass123"
        new_password:
          type: string
          description: 新密码
          example: "newPass456"
      nullable: false
    ChangePasswordResponse:
      type: object
      description: 修改密码响应结果
      properties:
        message:
          type: string
          description: 返回消息
          example: "密码更新成功"
      required: [message]
      nullable: false
    ResetPasswordRequest:
      type: object
      description: 忘记密码重置请求参数
      properties:
        email:
          type: string
          format: email
          description: 邮箱地址
          example: "zhangsan@example.com"
        code:
          type: string
          description: 邮箱验证码
          example: "123456"
        new_password:
          type: string
          description: 新密码
          example: "NewPass123"
      nullable: false
    ResetPasswordResponse:
      type: object
      description: 忘记密码重置响应结果
      properties:
        message:
          type: string
          description: 返回消息
          example: "密码重置成功"
      required: [message]
      nullable: false
    UserDetailRequest:
      type: object
      description: 用户详情请求参数
      properties:
        identity:
          type: string
          description: 用户身份标识
          example: "user_identity_12345"
      nullable: false
    UserDetailResponse:
      type: object
      description: 用户详情响应结果
      properties:
        name:
          type: string
          description: 用户名
          example: "zhangsan"
        email:
          type: string
          format: email
          description: 用户邮箱
          example: "zhangsan@example.com"
      required: [name, email]
      nullable: false
    SendVerificationCodeRequest:
      type: object
      description: 发送邮箱验证码请求参数
      properties:
        email:
          type: string
          format: email
          description: 邮箱地址
          example: "zhangsan@example.com"
      nullable: false
    SendVerificationCodeResponse:
      type: object
      description: 发送邮箱验证码响应结果
      properties:
        message:
          type: string
          description: 返回消息
          example: "验证码发送成功"
      required: [message]
      nullable: false
