// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"cloud_disk/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/detail",
				Handler: UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/reset",
				Handler: ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/update",
				Handler: ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send-verification-code",
				Handler: SendVerificationCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/users"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.FileAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/status",
					Handler: QueryUploadTaskStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/url",
					Handler: DownloadURLHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/file/move",
					Handler: UserFileMoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/file/name/update",
					Handler: UserFileNameUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/folder/create",
					Handler: UserFolderCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/folder/delete",
					Handler: UserFolderDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/list",
					Handler: UserFileListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/session/create",
					Handler: AgentCreateSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/session/list",
					Handler: AgentListSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/session/detail",
					Handler: AgentSessionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat",
					Handler: AgentChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resume",
					Handler: AgentResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/stream",
					Handler: AgentChatStreamHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resume/stream",
					Handler: AgentResumeStreamHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/file"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.FileAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateShareRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/download",
					Handler: ShareDownloadURLHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/get",
					Handler: GetShareRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/save",
					Handler: SaveResourceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/share"),
	)
}
