// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Name     string `json:"name,optional"`     // 用户名或邮箱
	Password string `json:"password,optional"` // 密码
}

type LoginResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type RegisterRequest struct {
	Name     string `json:"name,optional"`     // 用户名
	Email    string `json:"email,optional"`    // 邮箱
	Password string `json:"password,optional"` // 密码
	Code     string `json:"code,optional"`
}

type RegisterResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type SendVerificationCodeRequest struct {
	Email string `json:"email,optional"` // 邮箱地址
}

type SendVerificationCodeResponse struct {
	Message string `json:"message"` // 返回消息
}

type UploadFileRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type UploadFileResponse struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	Ext      string `json:"ext"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	RepositoryIdentity string `json:"repository_identity"`
}

type UserFileListRequest struct {
	Id   int64 `json:"id,optional"`
	Page int   `json:"page,optional"`
	Size int   `json:"size,optional"`
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type UserFileNameUpdateRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameUpdateResponse struct {
}

type UserFolderCreateRequest struct {
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
}

type UserRepositoryRequest struct {
	ParentId           int64  `json:"parent_id"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
}

type UserRepositoryResponse struct {
	Identity string `json:"identity"`
}
