// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Name     string `json:"name,optional"`     // 用户名或邮箱
	Password string `json:"password,optional"` // 密码
}

type LoginResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type RegisterRequest struct {
	Name     string `json:"name,optional"`     // 用户名
	Email    string `json:"email,optional"`    // 邮箱
	Password string `json:"password,optional"` // 密码
}

type RegisterResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
