// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordRequest struct {
	Identity    string `json:"identity"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Message string `json:"message"`
}

type CreateShareRecordRequest struct {
	Identity    string `json:"identity"`
	ExpiredTime int    `json:"expired_time"`
}

type CreateShareRecordResponse struct {
	Identity string `json:"identity"`
}

type DownloadURLRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	Expires            int    `json:"expires"`
}

type DownloadURLResponse struct {
	URL     string `json:"url"`
	Expires int    `json:"expires"`
}

type GetShareRecordRequest struct {
	Identity string `form:"identity"`
}

type GetShareRecordResponse struct {
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
}

type LoginRequest struct {
	Name     string `json:"name,optional"`     // 用户名或邮箱
	Password string `json:"password,optional"` // 密码
}

type LoginResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type RegisterRequest struct {
	Name     string `json:"name,optional"`     // 用户名
	Email    string `json:"email,optional"`    // 邮箱
	Password string `json:"password,optional"` // 密码
	Code     string `json:"code,optional"`
}

type RegisterResponse struct {
	Token string `json:"token"`
	Name  string `json:"name"`
}

type ResetPasswordRequest struct {
	Email       string `json:"email,optional"`
	Code        string `json:"code,optional"`
	NewPassword string `json:"new_password,optional"`
}

type ResetPasswordResponse struct {
	Message string `json:"message"`
}

type SaveResourceRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	ParentId           int64  `json:"parent_id"`
	Name               string `json:"name"`
}

type SaveResourceResponse struct {
	Identity string `json:"identity"`
}

type SendVerificationCodeRequest struct {
	Email string `json:"email,optional"` // 邮箱地址
}

type SendVerificationCodeResponse struct {
	Message string `json:"message"` // 返回消息
}

type ShareDownloadURLRequest struct {
	ShareIdentity string `json:"share_identity"`
	Expires       int    `json:"expires"`
}

type ShareDownloadURLResponse struct {
	URL     string `json:"url"`
	Expires int    `json:"expires"`
}

type UploadFileRequest struct {
	Hash     string `json:"hash,optional" form:"hash,optional"`
	Name     string `json:"name,optional" form:"name,optional"`
	Ext      string `json:"ext,optional" form:"ext,optional"`
	Size     int64  `json:"size,optional" form:"size,optional"`
	Path     string `json:"path,optional" form:"path,optional"`
	ParentId int64  `json:"parent_id,optional" form:"parent_id,optional"`
}

type UploadFileResponse struct {
	Message string `json:"message,optional"`
}

type UploadTaskStatusItem struct {
	Hash          string `json:"hash"`
	TaskKey       string `json:"task_key"`
	Name          string `json:"name"`
	Ext           string `json:"ext"`
	Size          int64  `json:"size"`
	State         int    `json:"state"`
	UploadedParts []int  `json:"uploaded_parts"`
	UpdatedAt     string `json:"updated_at"`
}

type QueryUploadTaskStatusRequest struct {
	Hash string `json:"hash,optional"`
}

type QueryUploadTaskStatusResponse struct {
	List []*UploadTaskStatusItem `json:"list"`
}

type AgentFileReference struct {
	FileIdentity string `json:"file_identity,omitempty"`
	Name         string `json:"name,omitempty"`
	URL          string `json:"url,omitempty"`
	MIMEType     string `json:"mime_type,omitempty"`
}

type AgentPendingInterrupt struct {
	InterruptID   string `json:"interrupt_id"`
	ToolName      string `json:"tool_name"`
	ArgumentsJSON string `json:"arguments_json"`
}

type AgentChatEvent struct {
	Type          string `json:"type"`
	Role          string `json:"role,omitempty"`
	Content       string `json:"content,omitempty"`
	ToolName      string `json:"tool_name,omitempty"`
	ArgumentsJSON string `json:"arguments_json,omitempty"`
}

type AgentSession struct {
	ID                 string `json:"id"`
	Title              string `json:"title"`
	PendingInterruptID string `json:"pending_interrupt_id,omitempty"`
	CreatedAt          string `json:"created_at,omitempty"`
	UpdatedAt          string `json:"updated_at,omitempty"`
}

type AgentConversationMessage struct {
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at,omitempty"`
}

type AgentChatRequest struct {
	SessionID   string               `json:"session_id,optional"`
	Message     string               `json:"message"`
	Attachments []AgentFileReference `json:"attachments,optional"`
}

type AgentResumeRequest struct {
	SessionID   string `json:"session_id"`
	InterruptID string `json:"interrupt_id"`
	Approved    bool   `json:"approved"`
	Reason      string `json:"reason,optional"`
}

type AgentChatResponse struct {
	Session          *AgentSession           `json:"session,omitempty"`
	Reply            string                  `json:"reply,omitempty"`
	Events           []*AgentChatEvent       `json:"events,omitempty"`
	PendingInterrupt *AgentPendingInterrupt  `json:"pending_interrupt,omitempty"`
	ReferencedFiles  []*AgentFileReference   `json:"referenced_files,omitempty"`
}

type AgentSessionListResponse struct {
	List []*AgentSession `json:"list"`
}

type AgentSessionDetailRequest struct {
	SessionID string `form:"session_id"`
}

type AgentSessionDetailResponse struct {
	Session  *AgentSession               `json:"session,omitempty"`
	Messages []*AgentConversationMessage `json:"messages,omitempty"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	RepositoryIdentity string `json:"repository_identity"`
	UpdatedAt          string `json:"updated_at"`
}

type UserFileListRequest struct {
	Id   int64 `json:"id,optional"`
	Page int   `json:"page,optional"`
	Size int   `json:"size,optional"`
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type UserFileMoveRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
}

type UserFileMoveResponse struct {
}

type UserFileNameUpdateRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameUpdateResponse struct {
}

type UserFolderCreateRequest struct {
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Id       int64  `json:"id"`
	Identity string `json:"identity"`
}

type UserFolderDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFolderDeleteResponse struct {
}
