openapi: 3.0.3
info:
  title: Core API - 用户中心服务
  description: 包含用户登录、注册核心接口
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8888/api/users
    description: 本地开发环境服务地址
paths:
  /login:
    post:
      summary: 用户登录接口
      description: 接收用户名/邮箱和密码，返回登录令牌和用户名
      operationId: LoginHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: 请求参数错误
        '401':
          description: 用户名或密码错误
  /register:
    post:
      summary: 用户注册接口
      description: 接收用户名、邮箱和密码，完成注册并返回令牌和用户名
      operationId: RegisterHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: 请求参数错误（如用户名已存在、邮箱格式非法）
components:
  schemas:
    LoginRequest:
      type: object
      description: 用户登录请求参数
      properties:
        username:
          type: string
          description: 用户名或邮箱
          example: "zhangsan"
        password:
          type: string
          description: 用户密码
          example: "123456Abc"
      nullable: false
    RegisterRequest:
      type: object
      description: 用户注册请求参数
      properties:
        username:
          type: string
          description: 用户名
          example: "zhangsan"
        email:
          type: string
          format: email
          description: 用户邮箱
          example: "zhangsan@example.com"
        password:
          type: string
          description: 用户密码
          example: "123456Abc"
      nullable: false
    LoginResponse:
      type: object
      description: 用户登录响应结果
      properties:
        token:
          type: string
          description: 登录令牌（用于后续接口认证）
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        username:
          type: string
          description: 用户名
          example: "zhangsan"
      required: [token, username]
      nullable: false
    RegisterResponse:
      type: object
      description: 用户注册响应结果
      properties:
        token:
          type: string
          description: 注册成功令牌（用于后续接口认证）
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        username:
          type: string
          description: 用户名
          example: "zhangsan"
      required: [token, username]
      nullable: false